// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recordsales.proto

package recordsales

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Sale struct {
	InstanceId           int32    `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	LastUpdateTime       int64    `protobuf:"varint,2,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sale) Reset()         { *m = Sale{} }
func (m *Sale) String() string { return proto.CompactTextString(m) }
func (*Sale) ProtoMessage()    {}
func (*Sale) Descriptor() ([]byte, []int) {
	return fileDescriptor_3961a399f18e1e66, []int{0}
}

func (m *Sale) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sale.Unmarshal(m, b)
}
func (m *Sale) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sale.Marshal(b, m, deterministic)
}
func (m *Sale) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sale.Merge(m, src)
}
func (m *Sale) XXX_Size() int {
	return xxx_messageInfo_Sale.Size(m)
}
func (m *Sale) XXX_DiscardUnknown() {
	xxx_messageInfo_Sale.DiscardUnknown(m)
}

var xxx_messageInfo_Sale proto.InternalMessageInfo

func (m *Sale) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

func (m *Sale) GetLastUpdateTime() int64 {
	if m != nil {
		return m.LastUpdateTime
	}
	return 0
}

func (m *Sale) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type Config struct {
	Sales                []*Sale  `protobuf:"bytes,1,rep,name=sales,proto3" json:"sales,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_3961a399f18e1e66, []int{1}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetSales() []*Sale {
	if m != nil {
		return m.Sales
	}
	return nil
}

func init() {
	proto.RegisterType((*Sale)(nil), "recordsales.Sale")
	proto.RegisterType((*Config)(nil), "recordsales.Config")
}

func init() { proto.RegisterFile("recordsales.proto", fileDescriptor_3961a399f18e1e66) }

var fileDescriptor_3961a399f18e1e66 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xce, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x80, 0x61, 0x62, 0x6d, 0x87, 0x2b, 0x88, 0x0d, 0x0e, 0xd9, 0x2c, 0x5d, 0xcc, 0x54, 0x50,
	0x1f, 0xc1, 0xc9, 0xb5, 0xea, 0x5c, 0x62, 0x73, 0x96, 0x83, 0xb6, 0x09, 0x49, 0x7c, 0x7f, 0x69,
	0x8a, 0xd0, 0xf1, 0xbe, 0x83, 0xbb, 0x1f, 0x0a, 0x87, 0x9d, 0x71, 0xda, 0xab, 0x01, 0x7d, 0x6d,
	0x9d, 0x09, 0x86, 0xe7, 0x2b, 0xaa, 0x7a, 0xd8, 0x3e, 0xd4, 0x80, 0xfc, 0x08, 0x39, 0x4d, 0x3e,
	0xa8, 0xa9, 0xc3, 0x96, 0xb4, 0x60, 0x25, 0x93, 0x69, 0x03, 0x7f, 0xba, 0x6b, 0x2e, 0x61, 0x3f,
	0x28, 0x1f, 0xda, 0xaf, 0xd5, 0x2a, 0x60, 0x1b, 0x68, 0x44, 0xb1, 0x29, 0x99, 0x4c, 0x9a, 0xdd,
	0xec, 0xaf, 0xc8, 0x4f, 0x1a, 0x91, 0x1f, 0x20, 0xb5, 0x8e, 0x3a, 0x14, 0x49, 0x3c, 0xb2, 0x0c,
	0xd5, 0x19, 0xb2, 0x9b, 0x99, 0x3e, 0xd4, 0xf3, 0x13, 0xa4, 0xf1, 0xb7, 0x60, 0x65, 0x22, 0xf3,
	0x4b, 0x51, 0xaf, 0x13, 0xe7, 0x98, 0x66, 0xd9, 0xbf, 0xb3, 0xd8, 0x7b, 0xfd, 0x05, 0x00, 0x00,
	0xff, 0xff, 0x7d, 0xe9, 0xed, 0xb1, 0xc4, 0x00, 0x00, 0x00,
}
