// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recordsales.proto

package recordsales

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Sale struct {
	InstanceId           int32    `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	LastUpdateTime       int64    `protobuf:"varint,2,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sale) Reset()         { *m = Sale{} }
func (m *Sale) String() string { return proto.CompactTextString(m) }
func (*Sale) ProtoMessage()    {}
func (*Sale) Descriptor() ([]byte, []int) {
	return fileDescriptor_3961a399f18e1e66, []int{0}
}

func (m *Sale) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sale.Unmarshal(m, b)
}
func (m *Sale) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sale.Marshal(b, m, deterministic)
}
func (m *Sale) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sale.Merge(m, src)
}
func (m *Sale) XXX_Size() int {
	return xxx_messageInfo_Sale.Size(m)
}
func (m *Sale) XXX_DiscardUnknown() {
	xxx_messageInfo_Sale.DiscardUnknown(m)
}

var xxx_messageInfo_Sale proto.InternalMessageInfo

func (m *Sale) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

func (m *Sale) GetLastUpdateTime() int64 {
	if m != nil {
		return m.LastUpdateTime
	}
	return 0
}

func (m *Sale) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type Config struct {
	Sales                []*Sale  `protobuf:"bytes,1,rep,name=sales,proto3" json:"sales,omitempty"`
	Archives             []*Sale  `protobuf:"bytes,2,rep,name=archives,proto3" json:"archives,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_3961a399f18e1e66, []int{1}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetSales() []*Sale {
	if m != nil {
		return m.Sales
	}
	return nil
}

func (m *Config) GetArchives() []*Sale {
	if m != nil {
		return m.Archives
	}
	return nil
}

type GetStaleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStaleRequest) Reset()         { *m = GetStaleRequest{} }
func (m *GetStaleRequest) String() string { return proto.CompactTextString(m) }
func (*GetStaleRequest) ProtoMessage()    {}
func (*GetStaleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3961a399f18e1e66, []int{2}
}

func (m *GetStaleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStaleRequest.Unmarshal(m, b)
}
func (m *GetStaleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStaleRequest.Marshal(b, m, deterministic)
}
func (m *GetStaleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStaleRequest.Merge(m, src)
}
func (m *GetStaleRequest) XXX_Size() int {
	return xxx_messageInfo_GetStaleRequest.Size(m)
}
func (m *GetStaleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStaleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStaleRequest proto.InternalMessageInfo

type GetStaleResponse struct {
	StaleSales           []*Sale  `protobuf:"bytes,1,rep,name=stale_sales,json=staleSales,proto3" json:"stale_sales,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStaleResponse) Reset()         { *m = GetStaleResponse{} }
func (m *GetStaleResponse) String() string { return proto.CompactTextString(m) }
func (*GetStaleResponse) ProtoMessage()    {}
func (*GetStaleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3961a399f18e1e66, []int{3}
}

func (m *GetStaleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStaleResponse.Unmarshal(m, b)
}
func (m *GetStaleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStaleResponse.Marshal(b, m, deterministic)
}
func (m *GetStaleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStaleResponse.Merge(m, src)
}
func (m *GetStaleResponse) XXX_Size() int {
	return xxx_messageInfo_GetStaleResponse.Size(m)
}
func (m *GetStaleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStaleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStaleResponse proto.InternalMessageInfo

func (m *GetStaleResponse) GetStaleSales() []*Sale {
	if m != nil {
		return m.StaleSales
	}
	return nil
}

type GetStateRequest struct {
	InstanceId           int32    `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStateRequest) Reset()         { *m = GetStateRequest{} }
func (m *GetStateRequest) String() string { return proto.CompactTextString(m) }
func (*GetStateRequest) ProtoMessage()    {}
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3961a399f18e1e66, []int{4}
}

func (m *GetStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateRequest.Unmarshal(m, b)
}
func (m *GetStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateRequest.Marshal(b, m, deterministic)
}
func (m *GetStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateRequest.Merge(m, src)
}
func (m *GetStateRequest) XXX_Size() int {
	return xxx_messageInfo_GetStateRequest.Size(m)
}
func (m *GetStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateRequest proto.InternalMessageInfo

func (m *GetStateRequest) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

type GetStateResponse struct {
	Sales                []*Sale  `protobuf:"bytes,1,rep,name=sales,proto3" json:"sales,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStateResponse) Reset()         { *m = GetStateResponse{} }
func (m *GetStateResponse) String() string { return proto.CompactTextString(m) }
func (*GetStateResponse) ProtoMessage()    {}
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3961a399f18e1e66, []int{5}
}

func (m *GetStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateResponse.Unmarshal(m, b)
}
func (m *GetStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateResponse.Marshal(b, m, deterministic)
}
func (m *GetStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateResponse.Merge(m, src)
}
func (m *GetStateResponse) XXX_Size() int {
	return xxx_messageInfo_GetStateResponse.Size(m)
}
func (m *GetStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateResponse proto.InternalMessageInfo

func (m *GetStateResponse) GetSales() []*Sale {
	if m != nil {
		return m.Sales
	}
	return nil
}

func init() {
	proto.RegisterType((*Sale)(nil), "recordsales.Sale")
	proto.RegisterType((*Config)(nil), "recordsales.Config")
	proto.RegisterType((*GetStaleRequest)(nil), "recordsales.GetStaleRequest")
	proto.RegisterType((*GetStaleResponse)(nil), "recordsales.GetStaleResponse")
	proto.RegisterType((*GetStateRequest)(nil), "recordsales.GetStateRequest")
	proto.RegisterType((*GetStateResponse)(nil), "recordsales.GetStateResponse")
}

func init() { proto.RegisterFile("recordsales.proto", fileDescriptor_3961a399f18e1e66) }

var fileDescriptor_3961a399f18e1e66 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0xa5, 0x48, 0xd3, 0x0c, 0x46, 0xcb, 0xc6, 0x03, 0x31, 0x1a, 0xc9, 0x5e, 0xe4, 0x62,
	0x0f, 0x78, 0xf4, 0x68, 0xa2, 0xe9, 0xc1, 0x0b, 0xe8, 0x19, 0x57, 0x18, 0xeb, 0x26, 0x14, 0x70,
	0x77, 0xda, 0x57, 0xf2, 0x35, 0xcd, 0x2e, 0xc1, 0xa2, 0xb1, 0xb6, 0xc7, 0xfd, 0x66, 0xf8, 0xe6,
	0x9f, 0x09, 0x10, 0x28, 0x2c, 0x1a, 0x55, 0x6a, 0x51, 0xa1, 0x9e, 0xb5, 0xaa, 0xa1, 0x86, 0xf9,
	0x03, 0xc4, 0x17, 0x70, 0x98, 0x89, 0x0a, 0xd9, 0x25, 0xf8, 0xb2, 0xd6, 0x24, 0xea, 0x02, 0x73,
	0x59, 0x86, 0x4e, 0xe4, 0xc4, 0x5e, 0x0a, 0x3d, 0x9a, 0x97, 0x2c, 0x86, 0x69, 0x25, 0x34, 0xe5,
	0xab, 0xb6, 0x14, 0x84, 0x39, 0xc9, 0x25, 0x86, 0xa3, 0xc8, 0x89, 0xdd, 0xf4, 0xd8, 0xf0, 0x67,
	0x8b, 0x9f, 0xe4, 0x12, 0xd9, 0x29, 0x78, 0xad, 0x92, 0x05, 0x86, 0xae, 0x95, 0x74, 0x0f, 0xfe,
	0x02, 0xe3, 0xbb, 0xa6, 0x7e, 0x93, 0x0b, 0x76, 0x05, 0x9e, 0x9d, 0x1d, 0x3a, 0x91, 0x1b, 0xfb,
	0x49, 0x30, 0x1b, 0x46, 0x34, 0x61, 0xd2, 0xae, 0xce, 0xae, 0x61, 0x22, 0x54, 0xf1, 0x2e, 0xd7,
	0xa8, 0xc3, 0xd1, 0xb6, 0xde, 0xef, 0x16, 0x1e, 0xc0, 0xc9, 0x03, 0x52, 0x46, 0x86, 0xe2, 0xc7,
	0x0a, 0x35, 0xf1, 0x7b, 0x98, 0x6e, 0x90, 0x6e, 0x9b, 0x5a, 0x23, 0x4b, 0xc0, 0xd7, 0x06, 0xe4,
	0x3b, 0x42, 0x80, 0xed, 0xca, 0xec, 0x95, 0x92, 0x5e, 0x4d, 0xbd, 0x7a, 0xe7, 0xc1, 0xf8, 0x6d,
	0x3f, 0x9b, 0x36, 0xb3, 0xf7, 0x5d, 0x3d, 0xf9, 0x74, 0xc0, 0x37, 0xef, 0x0c, 0xd5, 0x5a, 0x16,
	0xc8, 0xe6, 0x30, 0xe9, 0x17, 0x61, 0xe7, 0x3f, 0xbe, 0xfa, 0xb5, 0xf2, 0xd9, 0xc5, 0x96, 0x6a,
	0x97, 0x80, 0x1f, 0xb0, 0x47, 0x38, 0x32, 0xd4, 0xc8, 0x4d, 0xb6, 0x3f, 0x75, 0xf4, 0xaf, 0x8e,
	0x06, 0xba, 0xd7, 0xb1, 0xfd, 0xa9, 0x6e, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x18, 0xe9, 0x12,
	0x28, 0x69, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SaleServiceClient is the client API for SaleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SaleServiceClient interface {
	GetStale(ctx context.Context, in *GetStaleRequest, opts ...grpc.CallOption) (*GetStaleResponse, error)
	GetSaleState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
}

type saleServiceClient struct {
	cc *grpc.ClientConn
}

func NewSaleServiceClient(cc *grpc.ClientConn) SaleServiceClient {
	return &saleServiceClient{cc}
}

func (c *saleServiceClient) GetStale(ctx context.Context, in *GetStaleRequest, opts ...grpc.CallOption) (*GetStaleResponse, error) {
	out := new(GetStaleResponse)
	err := c.cc.Invoke(ctx, "/recordsales.SaleService/GetStale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saleServiceClient) GetSaleState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, "/recordsales.SaleService/GetSaleState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaleServiceServer is the server API for SaleService service.
type SaleServiceServer interface {
	GetStale(context.Context, *GetStaleRequest) (*GetStaleResponse, error)
	GetSaleState(context.Context, *GetStateRequest) (*GetStateResponse, error)
}

func RegisterSaleServiceServer(s *grpc.Server, srv SaleServiceServer) {
	s.RegisterService(&_SaleService_serviceDesc, srv)
}

func _SaleService_GetStale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleServiceServer).GetStale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordsales.SaleService/GetStale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleServiceServer).GetStale(ctx, req.(*GetStaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaleService_GetSaleState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleServiceServer).GetSaleState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordsales.SaleService/GetSaleState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleServiceServer).GetSaleState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SaleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recordsales.SaleService",
	HandlerType: (*SaleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStale",
			Handler:    _SaleService_GetStale_Handler,
		},
		{
			MethodName: "GetSaleState",
			Handler:    _SaleService_GetSaleState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recordsales.proto",
}
